# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  finger_joint:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_1:
    has_velocity_limits: true
    max_velocity: 3.14159265358979
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.75719614004311
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_3:
    has_velocity_limits: true
    max_velocity: 2.7925268031909298
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_4:
    has_velocity_limits: true
    max_velocity: 4.0142572795869604
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_5:
    has_velocity_limits: true
    max_velocity: 4.0142572795869604
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_6:
    has_velocity_limits: true
    max_velocity: 5.5850536063818499
    has_acceleration_limits: true
    max_acceleration: 5.0
  left_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  left_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  right_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  right_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  right_outer_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 0.0